title: "[Compilers]<Title>"
labels: ["compiler"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Have you check these sections of the docs?
        - [Compiler Documentation](https://docs.zksync.io/zk-stack/components/compiler/toolchain)

  - type: input
    id: team
    attributes:
      label: Team or Project
      description: Enter your team or project name (optional)
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Which compiler are you using?
      options:
        - label: zksolc
        - label: zkvyper
  - type: input
    id: version
    attributes:
      label: Which version of Solidity or Vyper?
      description: The Solidity or Vyper version from your config file
    validations:
      required: true
  - type: input
    id: zkversion
    attributes:
      label: zksolc/zkvyper version?
      description: The zksolc/zkvyper version from your config file
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Explain the issue
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Link to your repo?
      description: Though not mandatory, sharing a repository link with a README that details how to replicate the issue and the errors you're encountering will significantly expedite our support process.
    validations:
      required: false
