title: "[Deployment] <Title>"
labels: ["deployment"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Before proceeding, please check these links for contract verification help:
         - [Differences from Ethereum](https://era.zksync.io/docs/dev/building-on-zksync/contracts/differences-with-ethereum.html)
         - [Contract Deployment](https://era.zksync.io/docs/dev/building-on-zksync/contracts/contract-deployment.html)
         - [Quickstart Tutorial](https://era.zksync.io/docs/dev/building-on-zksync/hello-world.html)
 
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - 
        - Testnet
        - Mainnet
    validations:
      required: true

  - type: input
    id: block-number
    attributes:
      label: L2 block number
      description: Provide the L2 block number if applicable to your issue.
    validations:
      required: false
      
  - type: input
    id: zksolc-version
    attributes:
      label: zkSolc Version
    validations:
      required: true

  - type: input
    id: zksync-ethers-version
    attributes:
      label: zksync-ethers Version
    validations:
      required: true

  - type: textarea
    id: min-rep-ex
    attributes:
      label: Minimal Reproducible Code or Repo Link
      description: Please provide a minimal code example so that we can reproduce the issue or a link to your repo with the issues.
    validations:
      required: true

  - type: input
    id: other-evms
    attributes:
      label: Does this work on other EVMs? (If yes, please list at least 1 of them)
    validations:
      required: true
  
  - type: textarea
    id: contract-description
    attributes:
      label: Description of What Your Contract Does
    validations:
      required: false
      
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: If applicable, please provide any additional details
    validations:
      required: false
