title: "[Feature Request] <Title>"
labels: ["feature-request"]
body:
  - type: input
    id: team
    attributes:
      label: Team or Project
      description: Enter your team or project name (optional)
    validations:
      required: false
      
  - type: dropdown
    id: environment
    attributes:
      label: Network
      options:
        - 
        - ZKsync Lite
        - ZKsync Era
        - ZK Stack
    validations:
      required: true
      
  - type: textarea
    id: functionality-description
    attributes:
      label: Provide a brief description of the feature you would like to see implemented.
    validations:
      required: true
      
  - type: textarea
    id: specific-issue
    attributes:
      label: Who does this feature request benefit the most (users, developers, protocol, etc.)?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: If applicable, please provide any additional details
    validations:
      required: false
