title: "[General] <Title>"
labels: ["general"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Before proceeding, please check this link for general help:
         - [Developer Reference](https://docs.zksync.io/build/developer-reference)

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Testnet
        - Mainnet
    validations:
      required: true
      
  - type: input
    id: block-number
    attributes:
      label: L2 block number
      description: Provide the L2 block number if applicable to your issue.
    validations:
      required: false
      
  - type: textarea
    id: functionality-description
    attributes:
      label: Provide a brief description of the functionality you're trying to implement and the issue you are running into.
    validations:
      required: true

  - type: input
    id: repo-link
    attributes:
      label: Repo Link (Optional)
      description: Though not mandatory, sharing a repository link with a README that details how to replicate the issue and the errors you're encountering will significantly expedite our support process.
    validations:
      required: false
      
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: If applicable, please provide any additional details
    validations:
      required: false
